### PR TITLE
add nut in frameworks section

### PR DESCRIPTION
**Pull request by nanokind**
nut is a framework designed for micro frontends

Here is an example for demonstration

https://github.com/nut-project/nut/tree/master/examples

### CODE REVIEW

**Comment by nanokind** [comment]
@ChristianUlbrich ping~

**Comment by ChristianUlbrich** [comment]
Thx for the contrib; I will review until the end of the week!

**Comment by nanokind** [comment]
a live example for nut

with
https://nut.js.org/
and
https://fengzilong.github.io/nut-todomvc-example/

born: https://nut-compose.netlify.com/

**Comment by nanokind** [comment]
@ChristianUlbrich  Do you have time to have a look at this PR now 😂sorry for my disturbance

**Comment by ChristianUlbrich** [comment]
@fengzilong Plz. solve merge-conflicts. What is the main language that documentation for nut is in? Chinese? Sorry for me being so clueless...

**Comment by nanokind** [comment]
Conflicts resolved. yeah, its documentation is in Chinese for now, I'll try to provide an English version later

**Pull request merged**
